/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import BaseDatos.CRUD;
import BaseDatos.ConeccionBaseDatos;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.HeadlessException;
import java.sql.*;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author siviany
 */
public class Tabla extends javax.swing.JFrame {
        
        public static DefaultTableModel tabla = new DefaultTableModel(); 
        public boolean isCellEditable(int Fila, int Colum) {
            return false;
        }
    /**
     * Creates new form Tabla
     */
    public Tabla() {
        initComponents();
        cargarTitulosColumas();
        cargarDatos();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton1.setText("Menu principal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(2435, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        tabla.setColumnCount(0); //para limpiar los datos de la tabla columnas
        tabla.setRowCount(0); //para limpiar los datos de la tabla filas
        Menu menu =  new Menu();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tabla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
   public void cargarTitulosColumas(){
         tabla.addColumn("ID");   
         tabla.addColumn("Nombre_pelicula");
         tabla.addColumn("Año_Creacion");
         tabla.addColumn("Director");
         tabla.addColumn("Link_IBDM");
         tabla.addColumn("Genero");
         tabla.addColumn("Soundtranck");
         tabla.addColumn("Interprete_Sound");
         tabla.addColumn("Pistas");
         tabla.addColumn("Oscar_Cancion");
         tabla.addColumn("Banda_Sonora");
         tabla.addColumn("Inteprete_Banda");
         tabla.addColumn("Autor");
         tabla.addColumn("Oscar_Banda");
        this.jTable2.setModel(tabla);
    }
   public void cargarDatos() {
          //Variable que almacena los datos de la consulta
        String sql = "select Id,Nombre_pelicula,Año_Creacion,Director,Link_IBDM,Genero,Soundtranck,Interprete_Sound,Pistas,Oscar_Cancion,Banda_Sonora,Inteprete_Banda,Autor,Oscar_Banda from Principal";  //Consulta sql
        try {
            ConeccionBaseDatos objConeccionBaseDatos = new ConeccionBaseDatos();
           
            ResultSet resultado = objConeccionBaseDatos.sentencia.executeQuery(sql);  //Linea que ejecuta la consulta sql y almacena los datos en resultado

            while (resultado.next()) {                                    //Bucle que recorre la consulta obtenida
                String datos[] = new String[14]; 
                datos[0] = resultado.getString("Id");
                datos[1] = resultado.getString("Nombre_pelicula");
                datos[2] = resultado.getString("Año_Creacion");
                datos[3] = resultado.getString("Director");
                datos[4] = resultado.getString("Link_IBDM");
                datos[5] = resultado.getString("Genero");
                datos[6] = resultado.getString("Soundtranck");
                datos[7] = resultado.getString("Interprete_Sound");
                datos[8] = resultado.getString("Pistas");
                datos[9] = resultado.getString("Oscar_Cancion");
                datos[10] = resultado.getString("Banda_Sonora");
                datos[11] = resultado.getString("Inteprete_Banda");
                datos[12] = resultado.getString("Autor");
                datos[13] = resultado.getString("Oscar_Banda");
                tabla.addRow(datos);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al cargar los Datos\n" + ex);
        }
    }
}
